name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js and setup package manager
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install packages
        run: yarn install --immutable
      - name: Verify code formatting
        run: yarn prettier:verify && yarn lint
      - name: Build code
        run: yarn build
      - name: Run tests
        run: yarn test
